version: '3.7'

services:
  client:
    build: 
      context: ./client
      args:
        - VITE_BROKER_URL=http://localhost:8080
    networks:
      - iot-network
    ports:
      - "3000:3000"

  broker:
    build:
      context: ./broker
    hostname: broker
    networks:
      - iot-network
    ports:
      - "8080:8080"
      - "5310:5310/udp"

  lamp_sensor: &lamp_sensor
    build:
      context: ./sensor
      dockerfile: Lamp.Dockerfile
    environment:
      - BROKER_URL=172.18.192.1:5310
      - SENSOR_PORT=3333
    networks:
      - iot-network
    ports:
      - "3333:3333"
  
  air_cond_sensor:
    <<: *lamp_sensor
    build:
      context: ./sensor
      dockerfile: AirCond.Dockerfile
    ports:
      - "3334:3333"

networks:
  iot-network:
    driver: bridge